from emoji import emojize
smile = emojize(":blush:",use_aliases=True)
triste = emojize(":confused:",use_aliases=True)
question = emojize(":question:",use_aliases=True)
open_file_folder = emojize(":open_file_folder:",use_aliases=True)
success = emojize(":white_check_mark:",use_aliases=True)
no_entry = emojize(":no_entry:",use_aliases=True)
clessidra = emojize(":hourglass_flowing_sand:",use_aliases=True)
arrow_forward = emojize(":arrow_forward:",use_aliases=True)

door = emojize(":door:",use_aliases=True)
arrow_down = emojize(":arrow_down:",use_aliases=True)
arrow_up = emojize(":arrow_up:",use_aliases=True)
bookmark = emojize(":bookmark:",use_aliases=True)
black_mark = emojize(":heavy_check_mark:",use_aliases=True)
inbox_tray = emojize(":inbox_tray:",use_aliases=True)
ciclo = emojize(":arrows_counterclockwise:",use_aliases=True)
pallino_blu = emojize(":large_blue_circle:",use_aliases=True)
id_viola = emojize(":id:",use_aliases=True)
magnifier = emojize(":mag:",use_aliases=True)
plus = emojize(":heavy_plus_sign:",use_aliases=True)
link = emojize(":link:",use_aliases=True)
pause = u"\u23F8"